######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 5 11:23:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CImg.h mainwindow.h mesh.h numerical.h topalg.h
FORMS += mainwindow.ui
SOURCES += eField.cc main.cpp mainwindow.cpp mesh.cpp numerical.cpp topalg.cpp
